---
title: " Metadata exploration"
author: "Florentin Constancias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
    keep_md: yes
---

```{r setup, include=FALSE}
rm(list = ls())
gc()
# options(java.parameters = "-Xmx80000m")
```

```{r setup2, include=FALSE}
# knitr::opts_chunk$set(cache=TRUE)
# knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_chunk$set(dev = "ragg_png") # https://ragg.r-lib.org/index.html
##knitr::opts_chunk$set(fig.width = 6) #https://r4ds.had.co.nz/graphics-for-communication.html#figure-sizing
knitr::opts_chunk$set(fig.asp = 0.618)
knitr::opts_chunk$set(fig.show = "hold")
knitr::opts_chunk$set(fig.show = "70%")
knitr::opts_chunk$set(fig.align = "center")
options(rgl.useNULL = TRUE)
```

```{r setup3, include=FALSE}
library(rgl)
library(tidyverse)
library(phyloseq)
library(readxl)
```


```{r}
load(here::here("phyloseq.RData"))
```


```{r}
physeq %>% 
  microViz::ps_mutate(Group = recode(Group, `1. Slow` = "Slow", `2. Intermediate`  = "Moderate",  `3. Fast` = "Rapid")) %>% 
  microViz::ps_mutate(Group = fct_relevel(Group, c("Slow", "Moderate",  "Rapid"))) %>% 
  microViz::ps_mutate(time = recode(time, T1 = "Baseline", T2  = "2 weeks treatment",  T3 = "4 weeks")) %>% 
  microViz::ps_mutate(time = fct_relevel(time, c("Baseline", "2 weeks treatment",  "4 weeks")))-> physeq
```



```{r}
'StudieIIcsv_metadata.xlsx' %>% 
  here::here() %>% 
  read_excel(col_types = c('numeric', 
                           'text', 'text', 'numeric','numeric','numeric','numeric','numeric',
                           'numeric','numeric'))  %>% 
  filter(group == 1) %>% 
  mutate(ID = paste0("D", ID)) -> study2m

study2m$ID%>% unique() %>%  length()
```


```{r}
physeq %>% 
  sample_data() %>% 
  data.frame() %>% 
  rownames_to_column("tmp_id") %>% 
  left_join(study2m,
            join_by("id" == "ID")) %>% 
  column_to_rownames("tmp_id") -> sample_data(physeq)

```

```{r}
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R") 

tax_table(physeq) <- tax_table(physeq) %>% gsub(pattern=" ",replacement="") 


physeq %>% 
  phyloseq_get_strains() -> physeq
```


```{r}
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_varia.R") 

physeq %>% 
  generate_color_palette(var = "Group",
                         pal = "npg",
                         print = FALSE) -> treat_pal


physeq %>% 
  generate_color_palette(var = "time",
                         pal = "jco",
                         print = FALSE) -> time_pal

# pal <- c("treat_pal", treat_pal,
#          "time_pal", time_pal)
```

```{r}
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R") 

physeq %>%  sample_sums() %>%  min() -> min_lib

min_lib
```


```{r}
physeq %>%
  rarefy_even_depth(rngseed = 123,
                    sample.size = min_lib) -> physeq_rare # important to specify rngseed: random number generator for reproducibility
```

```{r}

physeq_rare %>%
  phyloseq_rarefaction_curves(stepsize = 100, 
                              color_data = "Group", 
                              facet_data = NULL) -> pr

pr + geom_vline(xintercept = min_lib,
                color = "red",
                linetype = "dashed", size=0.25) +
  facet_wrap(. ~ time) + ylab("ASV Richness")   +  theme(legend.position = "bottom")  -> plot_rare

plot_rare
```

```{r, include=FALSE}
plot_rare %>% 
  export::graph2ppt(append = TRUE,
                    width = 317.48031496 ,
                    height = 0.618 * 317.48031496  , paper = "A4",  scaling = 2,
                    file = "pre_plots.pptx")
```

```{r}
preprocess <- list("physeq" =physeq,"physeq_rare" =physeq_rare, "plot_rare" = plot_rare)
```

```{r}
save(physeq, physeq_rare, plot_rare, treat_pal, time_pal , file = here::here("save.RData"))
```

```{r}
sessionInfo()
```

