---
title: " Metadata exploration"
author: "Florentin Constancias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
    keep_md: yes
---

```{r setup, include=FALSE}
rm(list = ls())
gc()
# options(java.parameters = "-Xmx80000m")
```

```{r setup2, include=FALSE}
# knitr::opts_chunk$set(cache=TRUE)
# knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_chunk$set(dev = "ragg_png") # https://ragg.r-lib.org/index.html
##knitr::opts_chunk$set(fig.width = 6) #https://r4ds.had.co.nz/graphics-for-communication.html#figure-sizing
knitr::opts_chunk$set(fig.asp = 0.618)
knitr::opts_chunk$set(fig.show = "hold")
knitr::opts_chunk$set(fig.show = "70%")
knitr::opts_chunk$set(fig.align = "center")
options(rgl.useNULL = TRUE)
```

```{r setup3, include=FALSE}
library(rgl)
library(tidyverse)
library(phyloseq)
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_varia.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_heatmap.R")
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_alpha.R")

```


```{r}
load(here::here("save.RData"))
```

T1

```{r}
physeq_rare %>% 
    physeq_sel_tax_table(c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")) %>% 
  subset_samples(time == "Baseline") -> physeq_tax_only

```


```{r}


physeq_tax_only %>% 
  transform_sample_counts(function(x) x/sum(x) * 100) %>% 
  phyloseq_ampvis_heatmap(ntax = 15,
                          group_by = "Group",
                          transform = "identity",
                          tax_aggregate = "Genus",
                          plot_values = TRUE,
                          facet_by = c("time", "Group"))  -> p_heat_gen_t1

physeq_tax_only %>% 
  transform_sample_counts(function(x) x/sum(x) * 100) %>% 
  phyloseq_ampvis_heatmap(ntax = 15,
                          transform = "identity",
                          tax_aggregate = "Species",
                          group_by = "Group",
                          plot_values = TRUE,
                          facet_by = c("time", "Group"))  -> p_heat_sp_t1

p_heat_gen_t1
```

```{r}
p_heat_sp_t1
```

```{r, include=FALSE}
p_heat_gen_t1 %>% 
  export::graph2ppt(append = TRUE,
                    width = 317.48031496 * 1.75,
                    height = 0.618 * 317.48031496 * 3 , paper = "A4",  scaling = 2,
                    file = "heat.pptx")
```

```{r, include=FALSE}
p_heat_sp_t1 %>% 
  export::graph2ppt(append = TRUE,
                    width = 317.48031496 * 1.75,
                    height = 0.618 * 317.48031496 * 3 , paper = "A4",  scaling = 2,
                    file = "heat.pptx")
```


```{r}
p_heat_sp_t1
```


T2

```{r}
physeq_rare %>% 
    physeq_sel_tax_table(c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")) %>% 
  subset_samples(time == "2 weeks treatment") -> physeq_tax_only

```

```{r}
# 
# physeq_tax_only %>% 
#   transform_sample_counts(function(x) x/sum(x) * 100) %>% 
#   phyloseq_ampvis_heatmap(ntax = 4,
#                           group_by = "SampleID",
#                           transform = "identity",
#                           tax_aggregate = "Class",
#                           facet_by = c("time", "Group")) -> p_heat_class

physeq_tax_only %>% 
  transform_sample_counts(function(x) x/sum(x) * 100) %>% 
  phyloseq_ampvis_heatmap(ntax = 15,
                          group_by = "id",
                          transform = "identity",
                          tax_aggregate = "Genus",
                          plot_values = FALSE,
                          facet_by = c("time", "Group"))  -> p_heat_gen_t2

physeq_tax_only %>% 
  transform_sample_counts(function(x) x/sum(x) * 100) %>% 
  phyloseq_ampvis_heatmap(ntax = 15,
                          transform = "identity",
                          tax_aggregate = "Species",
                          group_by = "id",
                          plot_values = FALSE,
                          facet_by = c("time", "Group"))  -> p_heat_sp_t2

p_heat_gen_t2
```


```{r}
p_heat_sp_t2
```

```{r, include=FALSE}
p_heat_gen_t2 %>% 
  export::graph2ppt(append = TRUE,
                    width = 317.48031496 * 1.75,
                    height = 0.618 * 317.48031496 * 3 , paper = "A4",  scaling = 2,
                    file = "heat.pptx")
```

```{r, include=FALSE}
p_heat_sp_t2 %>% 
  export::graph2ppt(append = TRUE,
                    width = 317.48031496 * 1.75,
                    height = 0.618 * 317.48031496 * 3 , paper = "A4",  scaling = 2,
                    file = "heat.pptx")
```


T3

```{r}
physeq_rare %>% 
    physeq_sel_tax_table(c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")) %>% 
  subset_samples(time == "4 weeks") -> physeq_tax_only

```

```{r}
# 
# physeq_tax_only %>% 
#   transform_sample_counts(function(x) x/sum(x) * 100) %>% 
#   phyloseq_ampvis_heatmap(ntax = 4,
#                           group_by = "SampleID",
#                           transform = "identity",
#                           tax_aggregate = "Class",
#                           facet_by = c("time", "Group")) -> p_heat_class

physeq_tax_only %>% 
  transform_sample_counts(function(x) x/sum(x) * 100) %>% 
  phyloseq_ampvis_heatmap(ntax = 15,
                          group_by = "id",
                          transform = "identity",
                          tax_aggregate = "Genus",
                          plot_values = FALSE,
                          facet_by = c("time", "Group"))  -> p_heat_gen_t3

physeq_tax_only %>% 
  transform_sample_counts(function(x) x/sum(x) * 100) %>% 
  phyloseq_ampvis_heatmap(ntax = 15,
                          transform = "identity",
                          tax_aggregate = "Species",
                          group_by = "id",
                          plot_values = FALSE,
                          facet_by = c("time", "Group"))  -> p_heat_sp_t3

p_heat_gen_t3
```


```{r}
p_heat_sp_t3
```


```{r, include=FALSE}
p_heat_gen_t3 %>% 
  export::graph2ppt(append = TRUE,
                    width = 317.48031496 * 1.75,
                    height = 0.618 * 317.48031496 * 3 , paper = "A4",  scaling = 2,
                    file = "heat.pptx")
```

```{r, include=FALSE}
p_heat_sp_t3 %>% 
  export::graph2ppt(append = TRUE,
                    width = 317.48031496 * 1.75,
                    height = 0.618 * 317.48031496 * 3 , paper = "A4",  scaling = 2,
                    file = "heat.pptx")
```

```{r}
# ggpubr::ggarrange(p_heat_gen + ylab(NULL) + 
#                     theme(axis.title.x=element_blank(),
#                           axis.text.x=element_blank(),
#                           axis.ticks.x=element_blank(),
#                           legend.position = "none"),
#                   # p_heat_gen + 
#                   #   theme(
#                   #     strip.background = element_blank(),
#                   #     strip.text.x = element_blank(),
#                   #     legend.position = "none"
#                   #   ) +
#                     theme(axis.title.x=element_blank(),
#                           axis.text.x=element_blank(),
#                           axis.ticks.x=element_blank(),
#                           legend.position = "none"),
#                   p_heat_sp + 
#                     theme(
#                       strip.background = element_blank(),
#                       strip.text.x = element_blank(),
#                       legend.position = "none"
#                     ), 
#                   align = "v",
#                   ncol = 1, 
#                   heights = c(1.2, 2, 3),
#                   common.legend = FALSE) -> heat_all
# p_heat_sp
```


```{r, fig.height = 10}
heat_all <- list("p_heat_gen_t1" = p_heat_gen_t1, "p_heat_sp_t1" = p_heat_sp_t1,"p_heat_gen_t2" = p_heat_gen_t2, "p_heat_sp_t2" = p_heat_sp_t2, "p_heat_gen_t3" = p_heat_gen_t3, "p_heat_sp_t3" = p_heat_sp_t3)
```



```{r}
save(physeq, treat_pal, time_pal, physeq_rare ,alpha_save, plot_rare, meta, heat_all,file = here::here("save.RData"))
```

```{r}
sessionInfo()
```

